# Generated by Django 3.0.3 on 2020-05-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('hyperparameters', '0001_initial'), ('hyperparameters', '0002_auto_20200515_1449')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_alpha', models.FloatField(null=True)),
                ('end_alpha', models.FloatField(null=True)),
                ('epochs', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('start_alpha', 'end_alpha', 'epochs')},
            },
        ),
    ]
