# Generated by Django 3.0.3 on 2020-05-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_alpha', models.FloatField(null=True)),
                ('stop_alpha', models.FloatField(null=True)),
                ('epochs', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('start_alpha', 'stop_alpha', 'epochs')},
            },
        ),
    ]
