# Generated by Django 3.0.3 on 2020-05-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyperparameters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='stop_alpha',
            new_name='end_alpha',
        ),
        migrations.AlterUniqueTogether(
            name='parameters',
            unique_together={('start_alpha', 'end_alpha', 'epochs')},
        ),
    ]
