openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /:
    get:
      operationId: listapi_roots
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
  /{format}:
    get:
      operationId: Retrieveapi_root
      description: ''
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /hyperparameters/:
    get:
      operationId: listParameters
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    start_alpha:
                      type: number
                      nullable: true
                    end_alpha:
                      type: number
                      nullable: true
                    epochs:
                      type: integer
                      nullable: true
                  required:
                  - start_alpha
                  - end_alpha
                  - epochs
          description: ''
    post:
      operationId: createParameters
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema: &id001
              properties:
                start_alpha:
                  type: number
                  nullable: true
                end_alpha:
                  type: number
                  nullable: true
                epochs:
                  type: integer
                  nullable: true
              required:
              - start_alpha
              - end_alpha
              - epochs
          application/x-www-form-urlencoded:
            schema: *id001
          multipart/form-data:
            schema: *id001
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  start_alpha:
                    type: number
                    nullable: true
                  end_alpha:
                    type: number
                    nullable: true
                  epochs:
                    type: integer
                    nullable: true
                required:
                - start_alpha
                - end_alpha
                - epochs
          description: ''
  /hyperparameters{format}:
    get:
      operationId: listParameters
      description: ''
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    start_alpha:
                      type: number
                      nullable: true
                    end_alpha:
                      type: number
                      nullable: true
                    epochs:
                      type: integer
                      nullable: true
                  required:
                  - start_alpha
                  - end_alpha
                  - epochs
          description: ''
    post:
      operationId: createParameters
      description: ''
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: &id002
              properties:
                start_alpha:
                  type: number
                  nullable: true
                end_alpha:
                  type: number
                  nullable: true
                epochs:
                  type: integer
                  nullable: true
              required:
              - start_alpha
              - end_alpha
              - epochs
          application/x-www-form-urlencoded:
            schema: *id002
          multipart/form-data:
            schema: *id002
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  start_alpha:
                    type: number
                    nullable: true
                  end_alpha:
                    type: number
                    nullable: true
                  epochs:
                    type: integer
                    nullable: true
                required:
                - start_alpha
                - end_alpha
                - epochs
          description: ''
  /train/:
    get:
      operationId: listTrainSessions
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    start_time:
                      type: string
                      format: date-time
                      nullable: true
                    end_time:
                      type: string
                      format: date-time
                      nullable: true
                    status:
                      enum:
                      - 0
                      - 1
                      - 2
                      - -1
                      - 3
                    result:
                      type: number
                      nullable: true
                    error:
                      type: string
                      nullable: true
                    file_name:
                      type: string
                      nullable: true
                      maxLength: 255
                    parameters:
                      type: integer
                  required:
                  - parameters
          description: ''
  /train{format}:
    get:
      operationId: listTrainSessions
      description: ''
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    start_time:
                      type: string
                      format: date-time
                      nullable: true
                    end_time:
                      type: string
                      format: date-time
                      nullable: true
                    status:
                      enum:
                      - 0
                      - 1
                      - 2
                      - -1
                      - 3
                    result:
                      type: number
                      nullable: true
                    error:
                      type: string
                      nullable: true
                    file_name:
                      type: string
                      nullable: true
                      maxLength: 255
                    parameters:
                      type: integer
                  required:
                  - parameters
          description: ''
  /train/run/:
    get:
      operationId: runTrainSession
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  start_time:
                    type: string
                    format: date-time
                    nullable: true
                  end_time:
                    type: string
                    format: date-time
                    nullable: true
                  status:
                    enum:
                    - 0
                    - 1
                    - 2
                    - -1
                    - 3
                  result:
                    type: number
                    nullable: true
                  error:
                    type: string
                    nullable: true
                  file_name:
                    type: string
                    nullable: true
                    maxLength: 255
                  parameters:
                    type: integer
                required:
                - parameters
          description: ''
  /train/run{format}:
    get:
      operationId: runTrainSession
      description: ''
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  start_time:
                    type: string
                    format: date-time
                    nullable: true
                  end_time:
                    type: string
                    format: date-time
                    nullable: true
                  status:
                    enum:
                    - 0
                    - 1
                    - 2
                    - -1
                    - 3
                  result:
                    type: number
                    nullable: true
                  error:
                    type: string
                    nullable: true
                  file_name:
                    type: string
                    nullable: true
                    maxLength: 255
                  parameters:
                    type: integer
                required:
                - parameters
          description: ''
  /train/run/{id}/:
    get:
      operationId: runTrainSession
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this train session.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  start_time:
                    type: string
                    format: date-time
                    nullable: true
                  end_time:
                    type: string
                    format: date-time
                    nullable: true
                  status:
                    enum:
                    - 0
                    - 1
                    - 2
                    - -1
                    - 3
                  result:
                    type: number
                    nullable: true
                  error:
                    type: string
                    nullable: true
                  file_name:
                    type: string
                    nullable: true
                    maxLength: 255
                  parameters:
                    type: integer
                required:
                - parameters
          description: ''
  /train/run/{id}{format}:
    get:
      operationId: runTrainSession
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this train session.
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  start_time:
                    type: string
                    format: date-time
                    nullable: true
                  end_time:
                    type: string
                    format: date-time
                    nullable: true
                  status:
                    enum:
                    - 0
                    - 1
                    - 2
                    - -1
                    - 3
                  result:
                    type: number
                    nullable: true
                  error:
                    type: string
                    nullable: true
                  file_name:
                    type: string
                    nullable: true
                    maxLength: 255
                  parameters:
                    type: integer
                required:
                - parameters
          description: ''
  /train/{id}/:
    get:
      operationId: retrieveTrainSession
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this train session.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  start_time:
                    type: string
                    format: date-time
                    nullable: true
                  end_time:
                    type: string
                    format: date-time
                    nullable: true
                  status:
                    enum:
                    - 0
                    - 1
                    - 2
                    - -1
                    - 3
                  result:
                    type: number
                    nullable: true
                  error:
                    type: string
                    nullable: true
                  file_name:
                    type: string
                    nullable: true
                    maxLength: 255
                  parameters:
                    type: integer
                required:
                - parameters
          description: ''
  /train/{id}{format}:
    get:
      operationId: retrieveTrainSession
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this train session.
        schema:
          type: string
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  start_time:
                    type: string
                    format: date-time
                    nullable: true
                  end_time:
                    type: string
                    format: date-time
                    nullable: true
                  status:
                    enum:
                    - 0
                    - 1
                    - 2
                    - -1
                    - 3
                  result:
                    type: number
                    nullable: true
                  error:
                    type: string
                    nullable: true
                  file_name:
                    type: string
                    nullable: true
                    maxLength: 255
                  parameters:
                    type: integer
                required:
                - parameters
          description: ''
  /monitor/:
    get:
      operationId: listTrainSessions
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    start_time:
                      type: string
                      format: date-time
                      nullable: true
                    end_time:
                      type: string
                      format: date-time
                      nullable: true
                    status:
                      enum:
                      - 0
                      - 1
                      - 2
                      - -1
                      - 3
                    result:
                      type: number
                      nullable: true
                    error:
                      type: string
                      nullable: true
                    file_name:
                      type: string
                      nullable: true
                      maxLength: 255
                    parameters:
                      type: integer
                  required:
                  - parameters
          description: ''
  /monitor{format}:
    get:
      operationId: listTrainSessions
      description: ''
      parameters:
      - name: format
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      readOnly: true
                    start_time:
                      type: string
                      format: date-time
                      nullable: true
                    end_time:
                      type: string
                      format: date-time
                      nullable: true
                    status:
                      enum:
                      - 0
                      - 1
                      - 2
                      - -1
                      - 3
                    result:
                      type: number
                      nullable: true
                    error:
                      type: string
                      nullable: true
                    file_name:
                      type: string
                      nullable: true
                      maxLength: 255
                    parameters:
                      type: integer
                  required:
                  - parameters
          description: ''
