# Generated by Django 3.0.3 on 2020-05-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('train', '0001_initial'), ('train', '0002_auto_20200515_1602'), ('train', '0003_trainsession_file_name')]

    initial = True

    dependencies = [
        ('hyperparameters', '0002_auto_20200515_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (1, 'Loaded'), (2, 'Running'), (-1, 'Error'), (3, 'Finished')], default=0)),
                ('result', models.FloatField(null=True)),
                ('parameters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperparameters.Parameters')),
                ('error', models.TextField(null=True)),
                ('file_name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
