# Generated by Django 3.0.3 on 2020-05-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainsession',
            name='error',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trainsession',
            name='result',
            field=models.FloatField(null=True),
        ),
    ]
