# Generated by Django 3.0.3 on 2020-05-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_auto_20200515_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainsession',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
